### ISSUE TITLE
Can not sort tag column

### ISSUE THREAD

**Issue by Mordaur** [SubtitleEdit/XmlContentTranslator#10]
Could there be any way to sort the tag column?
I would like to translate a XML file with the following format:

```
<text>
         <originaltext>original text1</originaltext>
             <translation>translated text1</translation>
</text>
<text>
         <originaltext>original text2</originaltext>
             <translation>translated text2</translation>
</text>
```

Currently I have to ctrl+click all the <translation> tags (every other line), and then translate through google.
but for 100+ lines this is a major chore and prone to error.
It would be a lot easier to be able to sort by tags, then just shift+click all the rows that need translation at once.

**Comment by Mordaur** [comment]
I Temporarily fixed it for my use case, by setting the listview form sorting properties to a forced setting, so it will always sort ascending and compiling the source. But it would be nice to  have a 'on-header-click' sorting option.  Unfortunately I do not know how to code that.
So consider this as a feature request.
Also a 'translate with google' shortcut key could be handy.

For reference:

Before the fix:
https://ibb.co/y45CN6C

The fix:
https://ibb.co/zfzhcpc

after:
https://ibb.co/mqQncfL

**Comment by niksedk** [comment]
@Pandoriaantje: Could you try latest source?

**Comment by Mordaur** [comment]
> @Pandoriaantje: Could you try latest source?

Fixed. 
This makes my usecase much easier.

Thanks.

**Comment by niksedk** [comment]
Cool, thx for testing :)
