### ISSUE TITLE
Error when try translate

### ISSUE THREAD

**Issue by Makein** [SubtitleEdit/XmlContentTranslator#5]
---------------------------

---------------------------
Error getting/decoding translation from google!
---------------------------
ОК   
---------------------------

2 or more line of text would give this error

**Comment by niksedk** [comment]
What version are you using?
Is it all files that causes the problem for you?
A few screenshots would help.
Also, please attach the file you have problems with.

**Comment by Makein** [comment]
I use v1.8
Here sample with untranslated text
[a084.zip](https://github.com/SubtitleEdit/XmlContentTranslator/files/4920631/a084.zip)

**Comment by niksedk** [comment]
Did you add a source and target language?
![image](https://user-images.githubusercontent.com/1261331/87464090-d3012500-c612-11ea-88e2-47fafaf77a1b.png)

**Comment by Makein** [comment]
Check where 2 or 3 line text

**Comment by niksedk** [comment]
Ah, thx - see the error now.
