### ISSUE TITLE
Cannot Start with Version 1.9

### ISSUE THREAD

**Issue by nkh0472** [SubtitleEdit/XmlContentTranslator#6]
Double click the software, nothing happened.
Use Dnspy to debug, and pop up a window in the process of the software startup, indicating that the value of "InvalidArgument" which is -1 is invalid for index.
![screenshot 2021-01-16 092220](https://user-images.githubusercontent.com/67589323/104793419-6c391000-57dd-11eb-95b4-cbeda0d0a6a4.png)
If there is a .pdb file, maybe I can provide more information.

Here is my system's information:
```
>DotNetVersions.exe
Currently installed "classic" .NET Versions in the system:
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.04084

>ver
Microsoft Windows [Version 10.0.19042.746]
```

**Comment by niksedk** [comment]
Thx for the info - fixed in commit 0c3dde01e351cd41365bd4fc7a98218800044a36

Updated the release: https://github.com/SubtitleEdit/XmlContentTranslator/releases/download/1.9/XmlContentTranslator.zip
