### ISSUE TITLE
A High-resolution Icon Needed

### ISSUE THREAD

**Issue by nkh0472** [SubtitleEdit/XmlContentTranslator#7]
When using the large icon view in explorer, the low definition icon of this software looks not so beautiful compared with other icons. Therefore, I think it should be built with a clearer icon.
![](https://user-images.githubusercontent.com/67589323/120926186-7cab4200-c70e-11eb-91fd-0eaebe0c1030.png)

---
If you don't mind, you can use this icon. I have done a super-resolution processing for the original icon through [waifu2x](https://github.com/nagadomi/waifu2x).
![Web_XML_waifu2x_8x_2n_bmp](https://user-images.githubusercontent.com/67589323/120926457-8bdebf80-c70f-11eb-9d23-c849bea4b6cc.png)

[Web_XML_waifu2x_8x_2n_bmp.zip](https://github.com/SubtitleEdit/XmlContentTranslator/files/6604287/Web_XML_waifu2x_8x_2n_bmp.zip)
The distortion is pretty funny :)

**Comment by Makein** [comment]
> When using the large icon view in explorer, the low definition icon of this software looks not so beautiful compared with other icons. Therefore, I think it should be built with a clearer icon. ![](https://user-images.githubusercontent.com/67589323/120926186-7cab4200-c70e-11eb-91fd-0eaebe0c1030.png)
> 
> If you don't mind, you can use this icon. I have done a super-resolution processing for the original icon through [waifu2x](https://github.com/nagadomi/waifu2x). ![Web_XML_waifu2x_8x_2n_bmp](https://user-images.githubusercontent.com/67589323/120926457-8bdebf80-c70f-11eb-9d23-c849bea4b6cc.png)
> 
> [Web_XML_waifu2x_8x_2n_bmp.zip](https://github.com/SubtitleEdit/XmlContentTranslator/files/6604287/Web_XML_waifu2x_8x_2n_bmp.zip) The distortion is pretty funny :)

There many free and with good quality too
https://www.google.com/search?tbs=simg:CAESgAEafgsQsIynCBpiCmAIAxIonxKQAucFohKjCvEG4wjAA5QClQqQNLco6Da6KOc2mj27KOY2mD3BPRowYWGo8wg-r_1A06F5EQ-ysma23FSrf-AMsSO3F-N-WWG99KVsqffF5VFXPXmpZWj0OIAQMCxCOrv4IGgoKCAgBEgRhTZ8RDA&q=xml+&tbm=isch&sa=X&ved=2ahUKEwi7goXBv4P6AhVj_SoKHVE3DU4QjJkEegQIDBAC&biw=1280&bih=595&dpr=1.5

**Comment by niksedk** [comment]
XmlContentTranslator updated with new icon: https://github.com/SubtitleEdit/XmlContentTranslator/releases/download/1.11/XmlContentTranslator.zip
